### ISSUE TITLE
Not Working any More

### ISSUE THREAD

**Issue by TwinDimples** [KajanM/fresh-coupons#1]
Hey
Just wanted to know you that this chrome extension was working fine but for the last few days it does not fetch any new coupons....please check and update the extension
![Fresh Coupons Issue](https://user-images.githubusercontent.com/31496391/153349455-34b2da70-699c-4340-9d63-2a2bbb126496.PNG)
.

**Comment by soberguys** [comment]
Hi
Yes not working at all. Tried all browsers.

**Comment by simwyck** [comment]
Yes, same here, for several weeks now. This is a shame :(

**Comment by KajanM** [comment]
Fixed
