### ISSUE TITLE
The courses are not updated.

### ISSUE THREAD

**Issue by Mozaida** [KajanM/fresh-coupons#3]
The courses shown have not been refreshed or updated in the last 10 days. Please check for any bugs.

**Comment by KajanM** [comment]
the issue has been resolved
thanks for reporting

**Comment by Mozaida** [comment]
Thank you for your prompt response!

Your tool is truly a valuable asset for all users. I’d like to suggest adding an option to filter courses by language and category, which would further enhance its functionality and user experience.
